PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  displayName TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS passReasons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS passStatuses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS passes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  reasonId INTEGER NOT NULL,
  statusId INTEGER NOT NULL,
  validDate TEXT NOT NULL,
  comment TEXT,
  issuer TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  deletedAt TEXT,
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (reasonId) REFERENCES passReasons(id),
  FOREIGN KEY (statusId) REFERENCES passStatuses(id)
);

CREATE TABLE IF NOT EXISTS passHistory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  passId INTEGER NOT NULL,
  action TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  FOREIGN KEY (passId) REFERENCES passes(id)
);
